version: '3'
services:
  jobs_server:
    container_name: grpc_jobs_server
    image: basharsoft-my-grpc
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - grpc-jobs-service:/var/www/server
      - grpc-protos:/var/www/protos
    working_dir: /var/www/server
    command: >
      bash -c "composer install
      && composer spiral-gen-proto
      && composer run-grpc-server"

  jobs_client:
    container_name: grpc_jobs_client
    image: basharsoft-my-grpc
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - grpc-jobs-client:/var/www/client
      - grpc-protos:/var/www/protos
    working_dir: /var/www/client
    command: >
      bash -c "composer install
      && composer gen-proto
      && tail -f /dev/null"

volumes:
  grpc-protos:
    driver: local
    driver_opts:
      device: ./services/protos
      type: none
      o: bind

  grpc-jobs-service:
    driver: local
    driver_opts:
      device: ./services/server
      type: none
      o: bind

  grpc-jobs-client:
    driver: local
    driver_opts:
      device: ./services/client
      type: none
      o: bind
