ARG PHP_VERSION
FROM php:${PHP_VERSION}-fpm

ARG GO_VERSION
ARG GRPC_VERSION
ARG PROTOBUF_VERSION

RUN apt-get update -y &&\
    apt-get install -y git zip cmake zlib1g-dev\
    && apt-get -y autoremove\
    && apt-get clean\
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*\
    && php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

# Install GoLang
RUN curl -s https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz | tar -v -C /usr/local -xz
ENV PATH $PATH:/usr/local/go/bin

# Install Protobuf php-ext
RUN pecl install protobuf-${PROTOBUF_VERSION}\
    && docker-php-ext-enable protobuf\
    && pecl clear-cache\
    && rm -rf /tmp/pear

# Install Google gRPC tools (protoc & the php plugin)
RUN git clone --recurse-submodules --shallow-submodules --depth 1 -b v${GRPC_VERSION} https://github.com/grpc/grpc /root/grpc\
    && mkdir -p /root/grpc/cmake/build\
    && cd /root/grpc/cmake/build\
    && cmake ../..\
    && make protoc grpc_php_plugin\
    && mv /root/grpc/cmake/build/grpc_php_plugin /usr/local/bin/\
    && mv /root/grpc/cmake/build/third_party/protobuf/protoc-* /usr/local/bin/protoc\
    && rm -rf /root/grpc/

# Install Spiral gRPC tools & Roadrunner Server
ARG ROADRUNNER_VERSION
RUN git clone --depth 1 -b v${ROADRUNNER_VERSION} https://github.com/spiral/php-grpc.git /root/php-grpc\
    && /root/php-grpc/build.sh\
    && mv /root/php-grpc/protoc-gen-php-grpc /usr/local/bin/protoc-gen-php-grpc\
    && mv /root/php-grpc/rr-grpc /usr/local/bin/rr-grpc\
    && rm -rf /root/php-grpc/

# Removed the Go module cacheing
RUN go clean -modcache

WORKDIR /var/www/
EXPOSE 9001

CMD tail -f /dev/null
